import logo from '../assets/logo.png'
import error from '../assets/img/error.png'
import mastercard from '../assets/icons/mastercard.png'
import visa from '../assets/icons/visa.png'
import amex from '../assets/icons/amex.png'
import paypal from '../assets/icons/paypal.png'
import diners from '../assets/icons/diners.png'
import battery from '../assets/icons/battery.png'
import mesage from '../assets/icons/mesage.png'
import app_store from '../assets/img/app_store.png'
import google_play from '../assets/img/google_play.png'
import mobile_stores from '../assets/img/mobile_stores.png'
import mobile_screens from '../assets/img/mobile_screens.png'
import phone_screen_hero from '../assets/img/phone_screen_hero.png'
import phone_screen_only1 from '../assets/img/phone_screen_only1.png'
import phone_screen_only2 from '../assets/img/phone_screen_only2.png'
import phone_screen_only3 from '../assets/img/phone_screen_only3.png'
import phone_screen_only4 from '../assets/img/phone_screen_only4.png'
import phone_screen_only4_mobile from '../assets/img/phone_screen_only4_mobile.png'

export { logo, error, visa, mastercard, amex, paypal, diners, battery, mesage, app_store, google_play, mobile_stores, mobile_screens, phone_screen_only1, phone_screen_only2, phone_screen_only3, phone_screen_only4, phone_screen_only4_mobile, phone_screen_hero }
